#!/usr/bin/env osascript -l JavaScript

const HELP = `CLI for controlling the VOX music player

Usage:
  $ voxctl [command]

Commands:
  start               # Starts VOX
  quit                # Quits VOX
  play                # Begins playback
  pause               # Pauses playback
  togglePlay          # Toggles playback between playing and paused
  next                # Skips to the next track in the playlist
  previous            # Skips to the previous track in the playlist
  shuffle             # Toggles shuffle on or off
  playUrl URL         # Plays the specified URL
  addUrl URL          # Adds the specified URL to the playlist
  rewindForward       # Rewinds the current track forward
  rewindForwardFast   # Rewinds the current track forward fast
  rewindBackward      # Rewinds the current track backward
  rewindBackwardFast  # Rewinds the current track backward fast
  increaseVolume      # Increases the volume
  decreaseVolume      # Decreases the volume
  togglePlaylist      # Shows/hides the playlist
  info                # Displays information about the current track in JSON
  isRunning           # Prints true if VOX is open, otherwise false
  help                # Prints this information`

const COMMANDS = {
  start: vox => vox.activate(),
  quit: vox => vox.quit(),
  play: vox => vox.play(),
  pause: vox => vox.pause(),
  togglePlay: vox => vox.playpause(),
  next: vox => vox.next(),
  previous: vox => vox.previous(),
  shuffle: vox => vox.shuffle(),
  playUrl: (vox, [path]) => vox.playurl(path),
  addUrl: (vox, [path]) => vox.addurl(path),
  rewindForward: vox => vox.rewindforward(),
  rewindForwardFast: vox => vox.rewindforwardfast(),
  rewindBackward: vox => vox.rewindbackward(),
  rewindBackwardFast: vox => vox.rewindbackwardfast(),
  increaseVolume: vox => vox.increasvolume(),
  decreaseVolume: vox => vox.decreasevolume(),
  togglePlaylist: vox => vox.showhideplaylist(),
  info: vox => JSON.stringify(currentState(), null, 2),
  isRunning: vox => vox.running(),
}

const currentState = () => ({
  artist: vox.artist(),
  albumArtist: vox.albumArtist(),
  track: vox.track(),
  trackurl: vox.trackurl(),
  album: vox.album(),
  currentTime: vox.currentTime(),
  totalTime: vox.totalTime(),
  volume: vox.playerVolume(),
  uniqueID: vox.uniqueID(),
  playerState: vox.playerState(),
  repeatState: vox.repeatState(),
})

function run(argv) {
  const command = COMMANDS[argv[0]]
  if (!command) return HELP
  const vox = Application("Vox")
  vox.includeStandardAdditions = true
  return command(vox, argv.slice(1))
}

// vim: ft=javascript
