#!/usr/bin/env osascript -l JavaScript
const vox = Application("Vox")
vox.includeStandardAdditions = true

const HELP = `CLI for controlling the VOX music player

Usage:
  $ voxctl [command]

Commands:
  start               # Starts VOX
  quit                # Quits VOX
  play                # Begins playback
  pause               # Pauses playback
  togglePlay          # Toggles playback between playing and paused 
  next                # Skips to the next track in the playlist
  previous            # Skips to the previous track in the playlist
  shuffle             # Toggles shuffle on or off
  playUrl URL         # Plays the specified URL
  addUrl URL          # Adds the specified URL to the playlist
  rewindForward       # Rewinds the current track forward
  rewindForwardFast   # Rewinds the current track forward fast
  rewindBackward      # Rewinds the current track backward
  rewindBackwardFast  # Rewinds the current track backward fast
  increaseVolume      # Increases the volume
  decreaseVolume      # Decreases the volume
  togglePlaylist      # Shows/hides the playlist
  info                # Displays information about the current track in JSON
  isRunning           # Prints true if VOX is open, otherwise false
  help                # Prints this information`

const COMMANDS = {
  start: _ => vox.activate(),
  quit: _ => vox.quit(),
  play: _ => vox.play(),
  pause: _ => vox.pause(),
  togglePlay: _ => vox.playpause(),
  next: _ => vox.next(),
  previous: _ => vox.previous(),
  shuffle: _ => vox.shuffle(),
  playUrl: ([_, path]) => vox.playurl(path),
  addUrl: ([_, path]) => vox.addurl(path),
  rewindForward: _ => vox.rewindforward(),
  rewindForwardFast: _ => vox.rewindforwardfast(),
  rewindBackward: _ => vox.rewindbackward(),
  rewindBackwardFast: _ => vox.rewindbackwardfast(),
  increaseVolume: _ => vox.increasvolume(),
  decreaseVolume: _ => vox.decreasevolume(),
  togglePlaylist: _ => vox.showhideplaylist(),
  info: _ => `${JSON.stringify(currentState(), null, 2)}`,
  isRunning: _ => vox.running(),
  help: _ => HELP
}

const currentState = () => ({
  artist: vox.artist(),
  albumArtist: vox.albumArtist(),
  track: vox.track(),
  trackurl: vox.trackurl(),
  album: vox.album(),
  currentTime: vox.currentTime(),
  totalTime: vox.totalTime(),
  volume: vox.playerVolume(),
  uniqueID: vox.uniqueID(),
  playerState: vox.playerState(),
  repeatState: vox.repeatState()
})

function run(argv) {
  const command = COMMANDS[argv[0]]
  return command ? command(argv) : COMMANDS.help([])
}

// vim: ft=javascript
